-- One-time backfill of participant_heroes aggregate stats, derived from the real events
-- generated by scripts/generate_data.py. (players.last_played is set directly during
-- generation, not backfilled here.)

-- eliminations: count of 'kill' events where this session was the actor
UPDATE participant_heroes ph
SET eliminations = agg.cnt
FROM (
    SELECT actor_session_id, count(*) AS cnt
    FROM events
    WHERE event_type = 'kill'
    GROUP BY actor_session_id
) agg
WHERE ph.session_id = agg.actor_session_id;

-- deaths: count of 'death' events where this session was the actor
-- (death events are logged with the victim as actor_session_id)
UPDATE participant_heroes ph
SET deaths = agg.cnt
FROM (
    SELECT actor_session_id, count(*) AS cnt
    FROM events
    WHERE event_type = 'death'
    GROUP BY actor_session_id
) agg
WHERE ph.session_id = agg.actor_session_id;

-- number_of_ultimates_used: count of 'ultimate_used' events where this session was the actor
UPDATE participant_heroes ph
SET number_of_ultimates_used = agg.cnt
FROM (
    SELECT actor_session_id, count(*) AS cnt
    FROM events
    WHERE event_type = 'ultimate_used'
    GROUP BY actor_session_id
) agg
WHERE ph.session_id = agg.actor_session_id;

-- damage_done (Tank/Damage roles only): synthetic proxy summing base_damage across
-- kill + ability_used + ultimate_used events, with ultimates weighted 5x
UPDATE participant_heroes ph
SET damage_done = agg.total
FROM (
    SELECT e.actor_session_id,
           SUM(h.base_damage * CASE WHEN e.event_type = 'ultimate_used' THEN 5 ELSE 1 END) AS total
    FROM events e
    JOIN participant_heroes actor_ph ON actor_ph.session_id = e.actor_session_id
    JOIN heroes h ON h.hero_id = actor_ph.hero_id
    WHERE e.event_type IN ('kill', 'ability_used', 'ultimate_used')
      AND h.hero_role IN ('Tank', 'Damage')
    GROUP BY e.actor_session_id
) agg
WHERE ph.session_id = agg.actor_session_id;

-- healing_done (Support role only): same proxy formula, reusing base_damage as a
-- general "ability potency" value since the schema has no separate healing stat
UPDATE participant_heroes ph
SET healing_done = agg.total
FROM (
    SELECT e.actor_session_id,
           SUM(h.base_damage * CASE WHEN e.event_type = 'ultimate_used' THEN 5 ELSE 1 END) AS total
    FROM events e
    JOIN participant_heroes actor_ph ON actor_ph.session_id = e.actor_session_id
    JOIN heroes h ON h.hero_id = actor_ph.hero_id
    WHERE e.event_type IN ('kill', 'ability_used', 'ultimate_used')
      AND h.hero_role = 'Support'
    GROUP BY e.actor_session_id
) agg
WHERE ph.session_id = agg.actor_session_id;

-- assists: for each kill, count distinct teammate sessions (Tank/Damage role, excluding
-- the killer) who landed an ability_used/ultimate_used hit on the same victim within the
-- 3 seconds before the kill. Ability targeting rules already guarantee these are teammates
-- of the killer, since Tank/Damage abilities only ever target the opposing team.
UPDATE participant_heroes ph
SET assists = agg.cnt
FROM (
    SELECT assist_actor_session_id, count(*) AS cnt
    FROM (
        SELECT DISTINCT ability_e.actor_session_id AS assist_actor_session_id, kill_e.event_id AS kill_event_id
        FROM events kill_e
        JOIN events ability_e
          ON ability_e.target_session_id = kill_e.target_session_id
         AND ability_e.event_type IN ('ability_used', 'ultimate_used')
         AND ability_e.event_timestamp BETWEEN kill_e.event_timestamp - INTERVAL '3 seconds' AND kill_e.event_timestamp
         AND ability_e.actor_session_id != kill_e.actor_session_id
        JOIN participant_heroes assist_ph ON assist_ph.session_id = ability_e.actor_session_id
        JOIN heroes assist_h ON assist_h.hero_id = assist_ph.hero_id
        WHERE kill_e.event_type = 'kill'
          AND assist_h.hero_role IN ('Tank', 'Damage')
    ) distinct_assists
    GROUP BY assist_actor_session_id
) agg
WHERE ph.session_id = agg.assist_actor_session_id;
