INSERT INTO heroes (hero_name, hero_role, health, base_damage) VALUES
('Reinhardt', 'Tank', 550, 75),
('Winston', 'Tank', 500, 75),
('D.Va', 'Tank', 400, 50),
('Orisa', 'Tank', 550, 60),
('Roadhog', 'Tank', 700, 80),
('Sigma', 'Tank', 500, 70),
('Zarya', 'Tank', 400, 70),
('Doomfist', 'Tank', 450, 70),
('Ashe', 'Damage', 200, 80),
('Bastion', 'Damage', 200, 90),
('Hanzo', 'Damage', 200, 80),
('Junkrat', 'Damage', 200, 90),
('Cassidy', 'Damage', 200, 80),
('Mei', 'Damage', 250, 70),
('Pharah', 'Damage', 200, 80),
('Reaper', 'Damage', 250, 70),
('Soldier: 76', 'Damage', 200, 80),
('Sombra', 'Damage', 200, 80),
('Symmetra', 'Damage', 200, 80),
('Torbjörn', 'Damage', 250, 80),
('Tracer', 'Damage', 150, 90),
('Widowmaker', 'Damage', 175, 90),
('Ana', 'Support', 200, 70),
('Baptiste', 'Support', 200, 70),
('Brigitte', 'Support', 250, 60),
('Lúcio', 'Support', 200, 60),
('Mercy', 'Support', 200, 50),
('Moira', 'Support', 200, 60),
('Zenyatta', 'Support', 150, 70);


INSERT INTO abilities (hero_id, ability_name, ability_type, cooldown_seconds) VALUES
((SELECT hero_id FROM heroes WHERE hero_name = 'Reinhardt'), 'Rocket Hammer', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Reinhardt'), 'Fire Strike', 'Secondary', 6),
((SELECT hero_id FROM heroes WHERE hero_name = 'Reinhardt'), 'Earthshatter', 'Ultimate', 220),
((SELECT hero_id FROM heroes WHERE hero_name = 'Winston'), 'Tesla Cannon (short range)', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Winston'), 'Tesla Cannon (ranged)', 'Secondary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Winston'), 'Primal Rage', 'Ultimate', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'D.Va'), 'Fusion Cannons', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'D.Va'), 'Defense Matrix', 'Secondary', 1),
((SELECT hero_id FROM heroes WHERE hero_name = 'D.Va'), 'Self-Destruct', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Orisa'), 'Augmented Fusion Driver', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Orisa'), 'Energy Javelin', 'Secondary', 5),
((SELECT hero_id FROM heroes WHERE hero_name = 'Orisa'), 'Terra Surge', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Roadhog'), 'Scrap Gun', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Roadhog'), 'Chain Hook', 'Secondary', 8),
((SELECT hero_id FROM heroes WHERE hero_name = 'Roadhog'), 'Whole Hog', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Sigma'), 'Hyperspheres', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Sigma'), 'Kinetic Grasp', 'Secondary', 10),
((SELECT hero_id FROM heroes WHERE hero_name = 'Sigma'), 'Gravitic Flux', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Zarya'), 'Particle Cannon', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Zarya'), 'Particle Barrier', 'Secondary', 10),
((SELECT hero_id FROM heroes WHERE hero_name = 'Zarya'), 'Graviton Surge', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Doomfist'), 'Hand Cannon', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Doomfist'), 'Rocket Punch', 'Secondary', 3),
((SELECT hero_id FROM heroes WHERE hero_name = 'Doomfist'), 'Meteor Strike', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Ashe'), 'The Viper', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Ashe'), 'Coach Gun', 'Secondary', 6),
((SELECT hero_id FROM heroes WHERE hero_name = 'Ashe'), 'B.O.B.', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Bastion'), 'Configuration: Assault', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Bastion'), 'Configuration: Recon', 'Secondary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Bastion'), 'Configuration: Artillery', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Hanzo'), 'Storm Bow', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Hanzo'), 'Storm Arrows', 'Secondary', 6),
((SELECT hero_id FROM heroes WHERE hero_name = 'Hanzo'), 'Dragonstrike', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Junkrat'), 'Frag Launcher', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Junkrat'), 'Concussion Mine', 'Secondary', 8),
((SELECT hero_id FROM heroes WHERE hero_name = 'Junkrat'), 'Rip-Tire', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Cassidy'), 'Peacekeeper', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Cassidy'), 'Combat Roll', 'Secondary', 8),
((SELECT hero_id FROM heroes WHERE hero_name = 'Cassidy'), 'Deadeye', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Mei'), 'Endothermic Blaster', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Mei'), 'Cryo-Freeze', 'Secondary', 12),
((SELECT hero_id FROM heroes WHERE hero_name = 'Mei'), 'Blizzard', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Pharah'), 'Rocket Launcher', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Pharah'), 'Jump Jet', 'Secondary', 5),
((SELECT hero_id FROM heroes WHERE hero_name = 'Pharah'), 'Barrage', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Reaper'), 'Hellfire Shotguns', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Reaper'), 'Shadow Step', 'Secondary', 8),
((SELECT hero_id FROM heroes WHERE hero_name = 'Reaper'), 'Death Blossom', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Soldier: 76'), 'Heavy Pulse Rifle', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Soldier: 76'), 'Sprint', 'Secondary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Soldier: 76'), 'Tactical Visor', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Sombra'), 'Machine Pistol', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Sombra'), 'Hack', 'Secondary', 8),
((SELECT hero_id FROM heroes WHERE hero_name = 'Sombra'), 'EMP', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Symmetra'), 'Photon Projector', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Symmetra'), 'Sentry Turret', 'Secondary', 10),
((SELECT hero_id FROM heroes WHERE hero_name = 'Symmetra'), 'Photon Barrier', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Torbjörn'), 'Rivet Gun', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Torbjörn'), 'Deploy Turret', 'Secondary', 15),
((SELECT hero_id FROM heroes WHERE hero_name = 'Torbjörn'), 'Molten Core', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Tracer'), 'Pulse Pistols', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Tracer'), 'Blink', 'Secondary', 3),
((SELECT hero_id FROM heroes WHERE hero_name = 'Tracer'), 'Pulse Bomb', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Widowmaker'), 'Widow''s Kiss', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Widowmaker'), 'Grappling Hook', 'Secondary', 6),
((SELECT hero_id FROM heroes WHERE hero_name = 'Widowmaker'), 'Infra-Sight', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Ana'), 'Biotic Rifle', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Ana'), 'Sleep Dart', 'Secondary', 12),
((SELECT hero_id FROM heroes WHERE hero_name = 'Ana'), 'Nano Boost', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Baptiste'), 'Biotic Launcher', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Baptiste'), 'Regenerative Burst', 'Secondary', 15),
((SELECT hero_id FROM heroes WHERE hero_name = 'Baptiste'), 'Amplification Matrix', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Brigitte'), 'Rocket Flail', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Brigitte'), 'Repair Pack', 'Secondary', 6),
((SELECT hero_id FROM heroes WHERE hero_name = 'Brigitte'), 'Rally', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Lúcio'), 'Sonic Amplifier', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Lúcio'), 'Crossfade', 'Secondary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Lúcio'), 'Sound Barrier', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Mercy'), 'Caduceus Staff', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Mercy'), 'Guardian Angel', 'Secondary', 2),
((SELECT hero_id FROM heroes WHERE hero_name = 'Mercy'), 'Valkyrie', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Moira'), 'Biotic Grasp', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Moira'), 'Biotic Orb', 'Secondary', 8),
((SELECT hero_id FROM heroes WHERE hero_name = 'Moira'), 'Coalescence', 'Ultimate', 300),
((SELECT hero_id FROM heroes WHERE hero_name = 'Zenyatta'), 'Orb of Destruction', 'Primary', 0),
((SELECT hero_id FROM heroes WHERE hero_name = 'Zenyatta'), 'Orb of Discord', 'Secondary', 2),
((SELECT hero_id FROM heroes WHERE hero_name = 'Zenyatta'), 'Transcendence', 'Ultimate', 300);
